"""Build a matched display JSON/C header from caller-supplied local inputs."""
import argparse
import hashlib
import json
from pathlib import Path

def cp932_exact(c):
    try:
        return c.encode('cp932').decode('cp932') == c
    except UnicodeError:
        return False

def generate(translations, inventory, output, overrides=None):
    raw = Path(translations).read_bytes()
    chars = set()
    ids = set()
    for line in raw.decode('utf-8-sig').splitlines():
        row = json.loads(line)
        if row['id'] in ids:
            raise ValueError('duplicate translation ID: '+row['id'])
        ids.add(row['id'])
        chars.update(row['translation'])
    extra = Path(overrides).read_bytes() if overrides else b''
    if extra:
        for row in json.loads(extra.decode('utf-8-sig'))['items']:
            chars.update(row['replacement'])
    if '\0' in chars or any(0xe000 <= ord(c) < 0xe000+1880 for c in chars):
        raise ValueError('NUL or literal reserved display slot in translation')
    selected = sorted(c for c in chars if not cp932_exact(c))
    if len(selected) > 1880 or any(ord(c) > 0xffff or 0xd800 <= ord(c) <= 0xdfff for c in selected):
        raise ValueError('CP932 private display slot capacity or unsupported Unicode')
    rows = []
    for i, c in enumerate(selected):
        slot = 0xe000+i
        encoded = chr(slot).encode('cp932')
        if len(encoded) != 2 or not 0xf0 <= encoded[0] <= 0xf9:
            raise ValueError('private slot byte layout')
        rows.append({'unicode':ord(c), 'slot':slot, 'bytes_hex':encoded.hex()})
    reserved = {r['slot'] for r in rows}
    checked = 0
    inventory_raw = Path(inventory).read_bytes()
    for line in inventory_raw.decode('utf-8-sig').splitlines():
        row = json.loads(line)
        values = [row['source'], row.get('file', '')]
        values += [v['original_name'] for v in row['target']['archive_chain']]
        if any(ord(c) in reserved for value in values for c in value):
            raise ValueError('original source uses reserved slot: '+row['id'])
        checked += 1
    if not ids or not checked:
        raise ValueError('translations and full source inventory must be nonempty')
    result = {'format':'cp932-private-display-v1',
              'translations_sha256':hashlib.sha256(raw).hexdigest(),
              'overrides_sha256':hashlib.sha256(extra).hexdigest() if extra else None,
              'source_inventory_sha256':hashlib.sha256(inventory_raw).hexdigest(),
              'source_inventory_rows_checked':checked, 'source_slot_collisions':0,
              'characters':rows}
    dest = Path(output)
    dest.mkdir(parents=True, exist_ok=True)
    (dest/'native').mkdir(exist_ok=True)
    (dest/'display_mapping.json').write_text(json.dumps(result, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    header = '/* Generated by prepare_display_mapping.py; rebuild DLL and text together. */\n'
    header += '#define NEGA_DISPLAY_COUNT %d\n' % len(rows)
    header += 'static const WCHAR display_unicode[%d] = {\n' % max(1, len(rows))
    if not rows:
        header += '    0,\n'
    for i in range(0, len(rows), 12):
        header += '    '+', '.join('0x%04x'%r['unicode'] for r in rows[i:i+12])+',\n'
    header += '};\n'
    (dest/'native/display_mapping.h').write_text(header, encoding='ascii')
    return result

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--translations', required=True, type=Path)
    parser.add_argument('--inventory', required=True, type=Path)
    parser.add_argument('--overrides', type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    result = generate(args.translations, args.inventory, args.output, args.overrides)
    print(json.dumps({'mapped_characters':len(result['characters']), 'source_rows_checked':result['source_inventory_rows_checked']}))
